export const GRPC_SERVICE_NAME = {
  ENTERPRISE_USER_ERVICE: 'ENTERPRISE_USER_ERVICE',
  WALLET_ERVICE: 'WALLET_ERVICE',
  AUTHENTICATION_ERVICE: 'AUTHENTICATION_ERVICE',
  AUTHORIZATION_ERVICE: 'AUTHORIZATION_ERVICE',
} as const;
