name: Build and Publish Proto Package

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Proto Files
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Lint proto files
        run: npm run lint

      - name: Format check
        run: npm run format

  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Generate proto files
        run: npm run generate:proto

      - name: Build TypeScript
        run: npm run build:ts

      - name: Run tests
        run: npm test

      - name: Archive generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: |
            generated/
            dist/

  publish:
    runs-on: ubuntu-latest
    name: Publish to GitHub Packages
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
          scope: '@alloyx'

      - name: Install dependencies
        run: npm ci

      - name: Download generated files
        uses: actions/download-artifact@v4
        with:
          name: generated-files

      - name: Set package version for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=$(date +"%Y%m%d%H%M%S")
          npm version prerelease --preid=dev.$VERSION --no-git-tag-version

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    name: Create GitHub Release
    needs: publish
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Proto files package release ${{ github.ref }}
            
            ## Changes
            - Updated proto definitions
            - Generated TypeScript clients
            
            ## Installation
            ```bash
            npm install @alloyx/jupiter-grpc-protos@${{ github.ref }}
            ```
          draft: false
          prerelease: false
